---
- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    # ansible_python_interpreter: /usr/local/bin/python2
    application: nginxblue
  
  tasks:
    - name: Nginx setup
      apt: pkg=nginx state=installed update_cache=true
    - name: index.html copy
      template: src=index.html dest=/usr/share/nginx/html/index.html
    
    - name: create instances
      include_role:
        name: create_instance
    - name: setup DNS
      include_role:
        name: route53
   