---
- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/local/bin/python2
    application: nginxblue
  
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: create instances
      include_role:
        name: create_instance
    - name: setup DNS
      include_role:
        name: route53
   